name: Auto Deploy Insurance App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

     

      # ================= API GATEWAY =================
      - name: Build & Deploy API Gateway
        shell: powershell
        run: |
          cd api-gateway
          mvn clean package -DskipTests
          docker build -t api-gateway:latest .
          docker stop api-gateway -ErrorAction SilentlyContinue
          docker rm api-gateway -ErrorAction SilentlyContinue
          docker run -d -p 8082:8082 --name api-gateway api-gateway:latest

      