name: Deploy Insurance Services

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # ================= BUILD POLICY SERVICE =================
      - name: Build Policy Service
        shell: powershell
        run: |
          cd policy-service
          mvn clean package -DskipTests
          docker build -t policy-service:latest .
          cd ..

      # ================= BUILD API GATEWAY =================
      - name: Build API Gateway
        shell: powershell
        run: |
          cd gateway-service
          mvn clean package -DskipTests
          docker build -t api-gateway:latest .
          cd ..

      # ================= DEPLOY ALL SERVICES =================
      - name: Deploy using Docker Compose
        shell: powershell
        run: docker compose up -d --remove-orphans
          

      # ================= VERIFY =================
      - name: Verify Containers
        shell: powershell
        run: docker ps


         

      # # ================= UI =================
      # - name: Build & Deploy UI
      #   run: |
      #     cd insurance-ui
      #     npm install
      #     npm run build
      #     docker build -t insurance-ui:latest .
      #     docker stop insurance-ui -ErrorAction SilentlyContinue
      #     docker rm insurance-ui -ErrorAction SilentlyContinue
      #     docker run -d -p 4200:80 --name insurance-ui insurance-ui:latest
