name: Auto Deploy Insurance App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      
      # ================= API GATEWAY =================
      - name: Build & Deploy API Gateway
        run: |
          cd gateway-service
          mvn clean package -DskipTests
          docker build -t gateway-service:latest .
          docker stop gateway-service -ErrorAction SilentlyContinue
          docker rm gateway-service -ErrorAction SilentlyContinue
          docker run -d -p 8082:8082 --name gateway-service gateway-service:latest

     
